kind: pipeline
type: docker
name: deploy-nfc

trigger:
  branch:
    - dev
  event:
    - push
    - tag

steps:
  - name: publish docker image
    image: plugins/docker
    when:
      branch:
        - dev
      event:
        - push
    settings:
      username: developer
      password:
        from_secret: harbor_secret
      repo: harbor.catfoodworks.com/library/nfc
      registry: harbor.catfoodworks.com
      tags:
        - latest
      cache_from:
        - harbor.catfoodworks.com/library/nfc:latest

  - name: sync docker-compose.yaml
    image: appleboy/drone-scp
    when:
      branch:
        - dev
      event:
        - push
    depends_on:
      - publish docker image
    settings:
      host: 54.255.245.246
      port: 22
      username: app
      key:
        from_secret: ssh_key_prod
      source:
        - docker-compose.yaml
      target: /app/srv/nfc/

  - name: restart container
    image: "appleboy/drone-ssh"
    when:
      branch:
        - dev
      event:
        - push
    depends_on:
      - sync docker-compose.yaml
    settings:
      host: 54.255.245.246
      port: 22
      username: app
      key:
        from_secret: ssh_key_prod
      script:
        - export TAG_NFC=latest
        - cd /app/srv/nfc
        - docker compose pull
        - docker compose up -d
